//Sewni

import PDFDocument from "pdfkit";
import {
  getPlatformSummaryService,
  getMonthlyGrowthBasicService,
  getComplaintImpactService,
  getFullSystemReportService
} from "../services/analyticsService.js";

/* ===============================
   BASIC REPORTS
=============================== */

export const getPlatformSummary = async (req, res) => {
  try {
    const data = await getPlatformSummaryService();
    return res.status(200).json({ success: true, data });
  } catch (error) {
    console.error("Platform Summary Error:", error);
    return res.status(500).json({ success: false, message: "Server error" });
  }
};

export const getMonthlyGrowth = async (req, res) => {
  try {
    const data = await getMonthlyGrowthBasicService();
    return res.status(200).json({ success: true, data });
  } catch (error) {
    console.error("Monthly Growth Error:", error);
    return res.status(500).json({ success: false, message: "Server error" });
  }
};

export const getComplaintImpact = async (req, res) => {
  try {
    const data = await getComplaintImpactService();
    return res.status(200).json({ success: true, data });
  } catch (error) {
    console.error("Complaint Impact Error:", error);
    return res.status(500).json({ success: false, message: "Server error" });
  }
};

/* ===============================
   FULL SYSTEM REPORT
=============================== */

export const getFullSystemReport = async (req, res) => {
  try {
    const data = await getFullSystemReportService();
    return res.status(200).json({ success: true, data });
  } catch (error) {
    console.error("Full System Report Error:", error);
    return res.status(500).json({ success: false, message: "Server error" });
  }
};

/* ===============================
   GENERATE PDF REPORT
=============================== */

export const generatePDFReport = async (req, res) => {
  try {
    console.log("PDF generation started for admin:", req.admin?.username);
    
    if (!req.admin || !req.admin.username) {
      console.log("Unauthorized admin access attempt");
      return res.status(401).json({
        success: false,
        message: "Unauthorized admin"
      });
    }

    console.log("Fetching full report data...");
    const fullReportData = await getFullSystemReportService();
    console.log("Report data fetched successfully");
    
    const doc = new PDFDocument({ margin: 40 });

    // Set headers for client-side download
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="ReFeed-Analytics-Report-${new Date().toISOString().split('T')[0]}.pdf"`
    );
    res.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
    res.setHeader("Pragma", "no-cache");
    res.setHeader("Expires", "0");

    doc.pipe(res);

    /* ===========================
       HEADER
    ============================ */

    doc.fontSize(20).text("ReFeed Analytics & Impact Report", { align: "center" });
    doc.moveDown();

    doc.fontSize(12).text(`Generated By: ${req.admin.username}`);
    doc.text(`Generated On: ${new Date().toLocaleString()}`);
    doc.moveDown(2);

    /* ===========================
       PLATFORM SUMMARY
    ============================ */

    if (fullReportData.platformSummary) {
      doc.fontSize(16).text("Platform Summary");
      doc.moveDown(0.5);
      doc.fontSize(12);

      Object.entries(fullReportData.platformSummary).forEach(([key, value]) => {
        doc.text(`${key}: ${value}`);
      });

      doc.moveDown();
    }

    /* ===========================
       DONATION ANALYTICS
    ============================ */

    if (fullReportData.donationAnalytics) {
      doc.fontSize(16).text("Donation Analytics");
      doc.moveDown(0.5);
      doc.fontSize(12);

      doc.text(`Total Donations: ${fullReportData.donationAnalytics.totalDonations}`);
      doc.text(`Expired Donations: ${fullReportData.donationAnalytics.expiredDonations}`);
      doc.text(`Cancelled Donations: ${fullReportData.donationAnalytics.cancelledDonations}`);
      doc.moveDown(0.5);

      doc.text("Donation Status:");
      fullReportData.donationAnalytics.donationStatus?.forEach(item => {
        doc.text(`  ${item._id}: ${item.count}`);
      });

      doc.moveDown(0.5);

      doc.text("Food Type Breakdown:");
      fullReportData.donationAnalytics.foodTypeBreakdown?.forEach(item => {
        doc.text(`  ${item._id}: ${item.count} donations (${item.totalQuantity} units)`);
      });

      doc.moveDown(0.5);

      doc.text("Top Donors:");
      fullReportData.donationAnalytics.topDonors?.forEach(item => {
        doc.text(`  ${item._id}: ${item.donations} donations`);
      });

      doc.moveDown();
    }

    /* ===========================
       COMPLAINT IMPACT
    ============================ */

    if (fullReportData.complaintImpact) {
      doc.fontSize(16).text("Complaint Impact");
      doc.moveDown(0.5);
      doc.fontSize(12);

      doc.text("By Status:");
      fullReportData.complaintImpact.byStatus?.forEach(item => {
        doc.text(`  ${item._id}: ${item.count}`);
      });

      doc.moveDown();
    }

    console.log("PDF document ending...");
    doc.end();

  } catch (error) {
    console.error("Generate PDF Error:", error);
    return res.status(500).json({ success: false, message: error.message });
  }
};